export const USER_REPOSITORY_PROVIDE = Symbol('USER_REPOSITORY_PROVIDE');
export const USER_SERVICE_PROVIDE = Symbol('USER_SERVICE_PROVIDE');
export const USER_CREATE_USE_CASE_PROVIDE = Symbol('USER_CREATE_USE_CASE_PROVIDE');
